### PR TITLE
Depend on require_relative

### PR DESCRIPTION
**Pull request by michaelklishin**
For 1.8.7 compatibility.
require_relative will soon have no effect on 1.9, so it is a safe move.

### CODE REVIEW

**Comment by mark-moseley** [comment]
This linecache repo is specific to Ruby 1.9. I suggest you contact Rocky Bernstein over at RubyForge: http://rubyforge.org/projects/rocky-hacks/

**Comment by michaelklishin** [comment]
Mark,

So, who maintains linecache these days? I can contact Rocky but I first want to understand how linecache releases are made (and why). Do you mind explaining this? Thank you.

**Comment by mark-moseley** [comment]
For version 1.8, Rocky does, as far as I know. Based on the version history at rubygems (http://rubygems.org/gems/linecache/versions) someone has changed something recently. I don't know why.

**Comment by michaelklishin** [comment]
While I am trying to figure out who to contact, what do you think of the idea of making your fork 1.8.7-compatible? Current situation with 2 gems and two projects (one of which is on rubyforge with unknown maintainer) benefits no one.

**Comment by mark-moseley** [comment]
That is possible, in fact, one of my earlier linecache19 releases had that. I don't really have the time to maintain it, though. My priority is 1.9.

**Pull request closed without merging**
